# Generated by Django 4.2.5 on 2023-09-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='landingpagecontent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=None, verbose_name='')),
                ('imageheading', models.CharField(max_length=50)),
                ('imagedex', models.TextField()),
            ],
        ),
    ]
